double Frand();
double RandomGaussian();
void ImportTrainingSet(char *, double **, double **, int *);
void ImportW(char *, double ***, int *);
void ExportW(char *, double ***, int *);
double Sigmoid(double);
double SigmoidToDsigmoid(double);
void PopulateW(double ***);
void PopulateStates(double **, int *);
void PropagateNN(double ***, double *, double **);
void PrintStates(double **, int *);
void PrintW(double ***, int *);
double **AllocateState(int *);
double ***AllocateW(int *);
void CopyVector(double *, double *, int);
void GetFirstError(double *, double *, double *, int);
void BackPropagate(double **, double **, double ***, int *, int);
double Score(double ***, double **, double **);
void ReadConfigFile(char *filename);
void TestTrainingSet(double ***, double **, double **);
void FinalReport(double ***, double **, double **);
double *AllocateVector(long);
unsigned char *AllocateCvector(long);
int *AllocateIvector(long);
double **AllocateMatrix(long, long);
